### ISSUE TITLE
Electron requires an update to support Apple M1

### ISSUE THREAD

**Issue by david-grubhub** [mobxjs/mobx-devtools#111]
Running `yarn add -D mobx-devtools` throws an error:

```
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v10.1.3/electron-v10.1.3-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/david/dev/kiosk/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:400:28)
    at module.exports (/Users/david/dev/kiosk/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/david/dev/kiosk/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/Users/david/dev/kiosk/node_modules/@szmarczak/http-timer/source/index.js:37:11)
```

Looks like this dependency should be updated

**Comment by acascell** [comment]
any update on this would be greatly appreciated
