### ISSUE TITLE
The mobx version 5.15.1 cannot run this devtools

### ISSUE THREAD

**Issue by lppz-front-end** [mobxjs/mobx-devtools#75]
My mobx version is 5.15.1, open devtools blank, check the console, it shows an error
![image](https://user-images.githubusercontent.com/66299952/83941969-274e0380-a822-11ea-8ec6-08735405f5e0.png)

`window.js:8420 TypeError: Error in invocation of tabs.get(integer tabId, function callback): No matching signature.
    at whenTabLoaded (window.js:22868)
    at _inject (window.js:22883)
    at Object.inject (window.js:22934)
    at App.componentWillMount (window.js:8649)
    at Ng (window.js:8348)
    at fi (window.js:8387)
    at Rj (window.js:8474)
    at Qj (window.js:8457)
    at Kj (window.js:8457)
    at yj (window.js:8450)
Ci @ window.js:8420
Xi.c.callback @ window.js:8437
Cg @ window.js:8342
Ji @ window.js:8423
Sj @ window.js:8466
exports.unstable_runWithPriority @ window.js:8543
cg @ window.js:8333
Jj @ window.js:8459
yj @ window.js:8450
Ig @ window.js:8441
bk @ window.js:8492
(anonymous) @ window.js:8495
Nj @ window.js:8451
ik @ window.js:8495
exports.render @ window.js:8501
render @ window.js:8159
exports.default @ window.js:8168
(anonymous) @ window.js:22922
window.html#window:1 Error handling response: TypeError: Error in invocation of tabs.get(integer tabId, function callback): No matching signature.
    at whenTabLoaded (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:22868:15)
    at _inject (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:22883:10)
    at Object.inject (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:22934:14)
    at App.componentWillMount (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:8649:18)
    at Ng (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:8348:56)
    at fi (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:8387:159)
    at Rj (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:8474:490)
    at Qj (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:8457:265)
    at Kj (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:8457:194)
    at yj (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/window.js:8450:172)`

**Comment by FDiskas** [comment]
`"mobx": "^6.0.4",` same error - probably we need some tutorial how to proper integrate the tools :D

**Comment by zuziqiu** [comment]
5.9.0      The same situation

**Comment by MatanYemini** [comment]
The year is 2022, and I still get a white screen :(

**Comment by ImLunaHey** [comment]
anyone know the fix for this..?

**Comment by FDiskas** [comment]
Project is dead. Last commit 2y ago.
